version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Node.js 버전
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build  # React 앱 빌드

artifacts:
  files:
    - '**/*'
  base-directory: 'build'  # React 빌드 폴더